<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="http://example.com/order">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <OrderSummary xmlns="http://example.com/orderSummary">
            <ItemName>
                <xsl:value-of select="/ns0:Order/ns0:ItemName"/>
            </ItemName>
            <Quantity>
                <xsl:value-of select="/ns0:Order/ns0:Quantity"/>
            </Quantity>
            <ItemSummary>
                <xsl:value-of select="/ns0:Order/ns0:ItemName, /ns0:Order/ns0:UnitPrice"/>
            </ItemSummary>
        </OrderSummary>
    </xsl:template>
</xsl:stylesheet>